hw/char/riscv_htif: Fix format specifier for uint64_t
Use PRIx64 instead of %llx for uint64_t arguments to avoid
-Werror=format warnings on platforms where uint64_t is not
long long.

This fixes the cross-riscv64-system CI failure:

  ../hw/char/riscv_htif.c: In function 'htif_handle_tohost_write':
  ../hw/char/riscv_htif.c:175:38: error: format '%llx' expects argument
  of type 'long long unsigned int', but argument 2 has type 'uint64_t'
  {aka 'long unsigned int'} [-Werror=format=]

Fixes: d98f7a541c2c ("riscv_htif: reject invalid signature ranges (end <= begin)")
Tested-by: Tao Tang <tangtao1634@phytium.com.cn>
Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Reviewed-by: Alistair Francis <alistair.francis@wdc.com>
Signed-off-by: Chao Liu <chao.liu.zevorn@gmail.com>
Message-ID: <20260415134826.1742308-1-chao.liu.zevorn@gmail.com>
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>